@startuml
left to right direction
skinparam packageStyle rectangle

actor "Operador" as Op
actor "Atleta" as At
actor "Usuario" as User

' Herança entre atores
User <|-- Op
User <|-- At

rectangle "Sistema de Gestão das Olimpíadas" {
  
  usecase "HS10 - Autenticar" as AUTH
  
  usecase "HS01Gerenciar Competição" as GC
  usecase "HS01 - Cadastrar Competição" as C
  usecase "HS02 - Alterar Competição" as A
  usecase "HS03 - Cancelar Competição" as Can
  
  usecase "HS04 - Alocar Local" as AL
  usecase "HS05 - Registrar Resultados" as RR
  usecase "HS06 - Gerar Relatório de Medalhas" as GRM
  
  usecase "HS07 - Realizar Inscrição" as RI
  usecase "HS08 - Consultar Inscrições" as CI
  usecase "HS09 - Visualizar Resultados" as VR
  
  ' Relações
  Op --> GC
  Op --> AL
  Op --> RR
  Op --> GRM
  
  At --> RI
  At --> CI
  
  User --> VR
  
  ' Extends de Gerenciar Competicao (CRUD)
  C ..> GC : <<extend>>
  A ..> GC : <<extend>>
  Can ..> GC : <<extend>>
  
  ' Include de autenticação
  GC ..> AUTH : <<include>>
  AL ..> AUTH : <<include>>
  RR ..> AUTH : <<include>>
  GRM ..> AUTH : <<include>>
  RI ..> AUTH : <<include>>
  CI ..> AUTH : <<include>>
  
  ' Extends para regras
  C .> (HS01 - Verificar Conflito de Horário) : <<extends>>
  AL .> (HS04 - Verificar Disponibilidade Local) : <<extends>>
  RR .> (HS06 - Validar Pódio) : <<extends>>
  RI ..> (HS07 - Verificar País Representado) : <<include>>
}

@enduml
